# Autogenerated file
def render(escnamelist, itemlist):
    yield """
<!DOCTYPE html>
<html lang=\"en\" dir=\"ltr\">
<head>
  <meta charset=\"utf-8\">
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"/>
  <meta name=\"author\" content=\"MS\">
  <meta name=\"description\" content=\"Universal ESC Programmer\">
  <title>UniESC</title>
  <link rel=\"stylesheet\" href=\"static/index.css\">
</head>
<body>
<div id=\"wrapper\">
	<div id=\"top\">
		<input type=\"text\" class=\"info-box\" id=\"info\" disabled>
		<label class=\"label\" for=\"escname\">ESC-Model:</label>
		<select class=\"sel\" id=\"escname\" name=\"escname\" onchange=\"mkdisp()\">
			<option value=\"None\"> None </option>
	        """
    for esc in escnamelist:
        yield """
                <option> """
        yield str(esc)
        yield """ </option>
            """
    yield """
		</select> 
	</div>
	<div id=\"itmval\">
	    """
    for x in range(0, len(itemlist)):
        yield """
		    <label class=\"label\" id=\"LBL_"""
        yield str(itemlist[x])
        yield """\" for=\""""
        yield str(itemlist[x])
        yield """\"> """
        yield str(itemlist[x])
        yield """ </label>
		    <select class=\"sel\" id=\""""
        yield str(itemlist[x])
        yield """\" name=\""""
        yield str(itemlist[x])
        yield """\" onchange=\"update_escdata(this)\">
			    <option>---</option>
		    </select> 
		"""
    yield """
	</div>  
	<div id=\"bot\">
		<input type=\"button\" value=\"Reset\" onclick=\"reset()\" id=\"reset\" name=\"reset\"/>
		<input type=\"button\" value=\"Save\" onclick=\"save()\" id=\"save\" name=\"save\"/>
	</div>
</div>
<script type=\"text/javascript\" src=\"static/index.js\"></script>
</body>
</html>
"""
