# Autogenerated file
def render(*a, **d):
    yield """<!DOCTYPE html>
<html>
<head>
  <meta charset=\"utf-8\">
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
  <meta name=\"author\" content=\"MS\">
  <meta name=\"description\" content=\"Universal ESC Programmer\">
  <title>ESCProg</title>
  <link rel=\"stylesheet\" href=\"static/system.css\">
</head>

<body>
	
<div class=\"wrapper\"> 
    <div class=\"one\">
       <label class=\"label\" for=\"ssidlist\">Visiable Wifi Networks:</label>
       <select class=\"sel\" name=\"ssidlist\" id=\"ssidlist\" onChange=\"combo(this, 'ssid')\" onMouseOut=\"comboInit(this, 'ssid')\">
          <option>Run Scan first</option>
       </select>
    </div>
    <div class=\"onehalf\">  
       <label class=\"label\" for=\"ssid\">SSID:</label>
       <input class=\"sel\" name=\"ssid\" id=\"ssid\">
    </div>       
    <div class=\"two\">   
       <label class=\"label\" for=\"pw\">Enter Password:</label>
       <input class=\"sel\" name=\"pw\" id=\"pw\">
    </div>
    <div class=\"three\">     
        <input type=\"button\" value=\"Del\" id=\"wifibtn\" onclick=\"fnbtnremove()\" />
    </div>   
    <div class=\"four\">  
        <input type=\"button\" value=\"Scan\" id=\"wifibtn\" onclick=\"fnbtnscan()\" />
    </div>  
    <div class=\"five\">  
        <input type=\"button\" value=\"Add\" id=\"wifibtn\" onclick=\"fnbtnsave()\" />
    </div>
    <div class=\"six\" >
		<label class=\"label\" for=\"updatebtn\"><br></label>
        <input type=\"button\" value=\"Update\" id=\"updatebtn\" onclick=\"fnbtnota()\" />
    </div>
    <div class=\"seven\">
		<label class=\"label\" for=\"info\"><br></label>
	    <input type=\"text\" class=\"info-box\" id=\"info\" disabled>
    </div>
</div>

<script src=\"static/system.js\"></script>

</body>

</html>
"""
