# Autogenerated file
def render(*a, **d):
    yield """<!DOCTYPE html>
<html>
<head>
  <meta charset=\"utf-8\">
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
  <meta name=\"author\" content=\"MS\">
  <meta name=\"description\" content=\"Universal ESC Programmer\">
  <title>ESCProg</title>
  <link rel=\"stylesheet\" href=\"static/system.css\">
</head>
<script>
    function toggleField(hideObj,showObj)"""
    yield """{
      hideObj.disabled=true;        
      hideObj.style.display='none';
      showObj.disabled=false;   
      showObj.style.display='inline';
      showObj.focus();
    }
</script>
<body>
<div class=\"outline\">
    <div class=\"system\">
       <label for=\"selectssid\">Select SSID from List:</label>
       <select style=\"font-size: 20px; width: 100%;\" name=\"selectssid\" id=\"selectssid\"
            onchange=\"if(this.options[this.selectedIndex].value=='customOption')"""
    yield """{
              toggleField(this,this.nextSibling);
              this.selectedIndex='0';
            }\">
            <option></option>
            <option value=\"customOption\">Enter custom SSID</option>
       </select><input name=\"customssid\" id=\"customssid\" style=\"font-size: 20px; width: 100%; display:none;\" disabled=\"disabled\" 
            onblur=\"if(this.value=='')"""
    yield """{toggleField(this,this.previousSibling);}\">
       <label for=\"pw\">Enter Password:</label>
       <input name=\"pw\" id=\"pw\" style=\"font-size: 20px; width: 100%;\">
    </div>   
    <div class=\"btnblock\" id=\"wifibtn\">
        <button style=\"width: 30%;\" onclick=\"fnbtnremove()\">Del</button> 
        <button style=\"width: 30%;\" onclick=\"fnbtnscan()\">Scan</button> 
        <button style=\"width: 30%;\" onclick=\"fnbtnsave()\">Add</button> 
    </div>
    <h1>Check for Updates</h1>
    <div class=\"btnblock\" id=\"updatebtn\">
        <button style=\"width: 70%;\" onclick=\"fnbtnota()\">Update</button> 
    </div>
</div>
<script src=\"static/system.js\"></script>
</body>
</html>"""
