# Autogenerated file
def render(*a, **d):
    yield """<!DOCTYPE html>
<html>
<head>
  <meta charset=\"utf-8\">
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
  <meta name=\"author\" content=\"MS\">
  <meta name=\"description\" content=\"Universal ESC Programmer\">
  <title>ESCProg</title>
  <link rel=\"icon\" type=\"image/x-icon\" href=\"static/favicon.ico\">
  <link rel=\"stylesheet\" href=\"static/index.css\">
</head>
<script>
  function toggleField(hideObj,showObj)"""
    yield """{
    hideObj.disabled=true;        
    hideObj.style.display='none';
    showObj.disabled=false;   
    showObj.style.display='inline';
    showObj.focus();
  }
</script>
<body>
<div class=\"panel\">
    <nav id=\"topnav\">
         <a class=\"nav-link\" href=\"esc.html\">ESC</a>
         <a class=\"nav-link\" href=\"servo.html\">Servo</a>
         <a id=\"logo\" class=\"nav-link\" href=\"wifi.html\">WIFI</a>
         <a class=\"nav-link\" href=\"index.html\">About</a>
    </nav>
    <div class=\"wifi\">
       <label for=\"ssid\">Select SSID from List:</label>
       <select style=\"font-size: 20px; width: 100%;\" name=\"selectssid\" id=\"selectssid\"
            onchange=\"if(this.options[this.selectedIndex].value=='customOption')"""
    yield """{
              toggleField(this,this.nextSibling);
              this.selectedIndex='0';
            }\">
            <option>Scanning...</option>
            <option></option>
            <option value=\"customOption\">Enter custom SSID</option>
       </select><input name=\"customssid\" id=\"customssid\" style=\"font-size: 20px; width: 100%; display:none;\" disabled=\"disabled\" 
            onblur=\"if(this.value=='')"""
    yield """{toggleField(this,this.previousSibling);}\">
       <label for=\"pw\">Enter Password:</label>
       <input name=\"pw\" id=\"pw\" style=\"font-size: 20px; width: 100%;\">
    </div>   
    <div class=\"btnblock\">
        <button style=\"width: 70%;\" onclick=\"fnbtnsave()\">Save</button> 
    </div>
</div>
<script src=\"static/wifi.js\"></script>
</body>
</html>"""
